import { FormProvider } from "@/context/Formcontext";
import type { Metadata } from "next";
import Navbar from "./Navbar/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Navbar/>
        <FormProvider>
        {children}
        </FormProvider>
        </body>
    </html>
  );
}
